import {
  Sparkles,
  Network,
  MapPin,
  ShieldAlert,
  HeartPulse,
  ClipboardCheck,
  ClipboardList,
  Database,
  DoorOpen,
  FileMinus2,
  Users,
  Gauge,
  Scale,
  CalendarCheck,
  Bell,
  Link2,
  Watch,
  Building2,
  Route,
  Activity,
  Brain,
  Eye,
  TrendingUp,
  ScrollText,
  ShieldCheck,
  Footprints,
  BarChart3,
  Layers,
  type LucideIcon,
} from "lucide-react";

// Shared registry. Pages pass icon names (strings) across the RSC
// boundary; client components do the lookup here. Add a new key when
// a page wants an icon that isn't listed.
export const ICONS: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  network: Network,
  mapPin: MapPin,
  shieldAlert: ShieldAlert,
  heartPulse: HeartPulse,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  database: Database,
  doorOpen: DoorOpen,
  fileMinus: FileMinus2,
  users: Users,
  gauge: Gauge,
  scale: Scale,
  calendarCheck: CalendarCheck,
  bell: Bell,
  link: Link2,
  watch: Watch,
  building: Building2,
  route: Route,
  activity: Activity,
  brain: Brain,
  eye: Eye,
  trendingUp: TrendingUp,
  scrollText: ScrollText,
  shieldCheck: ShieldCheck,
  footprints: Footprints,
  barChart: BarChart3,
  layers: Layers,
};

export type CapabilityIconName = keyof typeof ICONS;
