INSERT INTO public.news_articles (slug, title, category, excerpt, content, featured, published, published_at, meta_title, meta_description, keywords, og_image_url, author_name) VALUES ('talitrix-selected-as-a-gps-provider-for-floridas-20th-judicial-circuit', 'Talitrix Selected as a GPS Provider for Florida’s 20th Judicial Circuit', 'Announcement', $tt9tn6249$ALPHARETTA, GA – October 7, 2025 – Talitrix has been approved as a preferred electronic monitoring (EM) vendor with the only wrist-worn device in Florida’s 20th Judicial Circuit, which serves Charlotte, Collier, Glades, Hendry and Lee Counties.$tt9tn6249$, $tt3whzqf9$ALPHARETTA, GA – October 7, 2025 – Talitrix has been approved as a preferred electronic monitoring (EM) vendor with the only wrist-worn device in Florida’s 20th Judicial Circuit, which serves Charlotte, Collier, Glades, Hendry and Lee Counties.

As an approved vendor, Talitrix can now be selected to provide electronic monitoring solutions for individuals on probation or pretrial release. Talitrix offers both traditional ankle monitors and its wrist-worn GPS devices, giving participants the ability to choose a monitoring solution that best fits their lifestyle while still meeting court requirements.

In addition to offering participants a choice of hardware, Talitrix delivers powerful data tools that empower justice system professionals to make informed decisions. Talitrix offers The Talitrix Score, a data-driven tool based on participant behavioral patterns during their time on the Talitrix system. This score gives probation officers, attorneys, and judges within the 20th Judicial Circuit the ability to make faster and more informed decisions on individuals who are monitored by Talitrix.

“We are looking forward to serving Florida's 20th Judicial Circuit. Their approval of our Talitrix Solution Suite gives us the opportunity to advance its commitment to accountability, public safety, and rehabilitation,” said Justin Hawkins, Chief Executive Officer at Talitrix. “By providing both innovative technology and data-driven insights, we aim to equip judges, attorneys, and probation officers with the tools they need to drive better outcomes for the communities they serve.”

About Talitrix

Talitrix, the global leader in GPS wrist wearable technology, is transforming the justice system through innovation and accountability. Our industry first wrist-wearable GPS monitoring device delivers real-time behavioral analytics designed to improve compliance, reduce stigma, and enhance public safety. Its platform is trusted by law enforcement, courts, corrections, and community supervision programs nationwide. With a strong foundation in integrity, innovation, and social responsibility, Talitrix remains committed to safer communities and brighter futures.

Media Contact:

Micah Gravley: micah@talitrix.com

Madelyn Oliver: madelyn@talitrix.com$tt3whzqf9$, false, true, '2025-10-07T14:59:10.147Z', 'Talitrix Selected as a GPS Provider for Florida’s 20th Judicial Circuit', 'ALPHARETTA, GA – October 7, 2025 – Talitrix has been approved as a preferred electronic monitoring (EM) vendor with the only wrist-worn device in Florida’s 20th', NULL, '/news-images/talitrix-selected-as-a-gps-provider-for-floridas-20th-judicial-circuit.png', 'Carter Jarrett');