INSERT INTO public.news_articles (slug, title, category, excerpt, content, featured, published, published_at, meta_title, meta_description, keywords, og_image_url, author_name) VALUES ('talitrix-and-securus-monitoring-join-expertise-to-deliver-new-standard-in-electronic-monitoring', 'Talitrix and Securus Monitoring Join Expertise to Deliver New Standard in Electronic Monitoring', 'Announcement', $tii987igq$Alpharetta, Georgia, June 28, 2024 – Talitrix, the global leader in GPS wrist wearable technology, is pleased to announce its nationwide alliance with Securus Monitoring, a leading provider of technology solutions for public safety, law enforcement, and community supervision. This agreement creates dual integration that enables a twenty-first century approach to electronic monitoring supervision, allowing government agencies to select ankle, wrist, and or mobile applications on a single software$tii987igq$, $ty5c3az6s$Alpharetta, Georgia, June 28, 2024 – Talitrix, the global leader in GPS wrist wearable technology, is pleased to announce its nationwide alliance with Securus Monitoring, a leading provider of technology solutions for public safety, law enforcement, and community supervision. This agreement creates dual integration that enables a twenty-first century approach to electronic monitoring supervision, allowing government agencies to select ankle, wrist, and or mobile applications on a single software platform.

“By combining our state-of-the-art innovation with the size, scope and infrastructure of Securus Monitoring, we see an opportunity to accelerate the use of electronic monitoring throughout the United States and ultimately drive thought leadership,” says Justin Hawkins, CEO, Talitrix. “From small pretrial populations to large state agencies, we could not be more excited to serve our criminal justice partners.”

Since its establishment in 2020, Talitrix has been at the forefront of transforming electronic monitoring services for inmates, pre-trial detainees, and parolees. While serving over 100 government agencies across the southeast utilizing Talitrix equipment, the company has emerged as the largest provider of electronic monitoring solutions in the region.

The Talitrix solution suite comprises supervision web-based software, mobile applications, and state-of-the-art wearable bands equipped with tamper-resistant features, real-time tracking, and biometric data capture capabilities. These innovative technologies not only enhance monitoring effectiveness, but they also contribute to reducing the negative stigma associated with electronic monitoring.

“Our relationship with Talitrix supports Securus’ commitment to provide our customers with the most innovative civil and criminal justice technology solutions that improve public safety and modernize the criminal justice experience,” said Kevin Elder, President, Securus Technologies. “Customers and consumers alike are looking for wearable solutions, and the wrist wearable solution from Talitrix is a forward-thinking approach that can improve outcomes for specific populations in the criminal justice market.”

For more information about Talitrix and its industry-leading solutions, please visit talitrix.com and to learn more about Securus Monitoring’s comprehensive monitoring and investigative solutions, visit https://www.aventiv.com/securus-technologies/.

About Talitrix

Talitrix is the global leader in GPS wrist wearable technology, dedicated to revolutionizing electronic monitoring services for law enforcement agencies, government entities, and rehabilitation facilities worldwide. Headquartered in Alpharetta, Georgia, Talitrix has proudly partnered with local governments and law enforcement to deliver cutting-edge technology that transforms the electronic monitoring landscape.

About Securus Technologies

Headquartered in Plano, Texas, Securus Technologies® (Securus) is an Aventiv Technologies company that serves more than 1,800 public safety, law enforcement, and corrections agencies as well as over 1,000,000 incarcerated individuals across North America. Founded in 1986, Securus offers innovative solutions like phone and video connections and e-messaging, which connect family and friends to their incarcerated loved ones. Our secure monitoring and investigative solutions aid law enforcement and correctional facility staff in their operations and efforts to maintain public safety in communities nationwide. As the pioneers of tablet technology, Securus introduced the first corrections-grade tablet in 2011, revolutionizing how communication, entertainment, reentry, and educational resources are deployed in complex corrections environments, elevating efficiency in operations and stronger reentry outcomes. For more information, please visit https://www.aventiv.com/securus-technologies/ or follow us on social media on LinkedIn, YouTube, and Facebook.$ty5c3az6s$, false, true, '2024-06-28T14:08:27.918Z', 'Talitrix and Securus Monitoring Join Expertise to Deliver New Standard in Electronic Monitoring', 'Alpharetta, Georgia, June 28, 2024 – Talitrix, the global leader in GPS wrist wearable technology, is pleased to announce its nationwide alliance with Securus M', NULL, '/news-images/talitrix-and-securus-monitoring-join-expertise-to-deliver-new-standard-in-electronic-monitoring.png', 'Avery Finley');